# Generated by Django 5.1.2 on 2024-10-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shoes_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
                ('Shoes_Images', models.ImageField(blank=True, null=True, upload_to='Category_images')),
            ],
        ),
    ]
