# Generated by Django 5.1.2 on 2024-10-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoes_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Category', models.CharField(blank=True, max_length=200, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Country_of_origin', models.CharField(blank=True, max_length=200, null=True)),
                ('Manufactured_By', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
                ('MRP', models.IntegerField(blank=True, null=True)),
                ('Product_Image_1', models.ImageField(blank=True, null=True, upload_to='Product_Images')),
                ('Product_Image_2', models.ImageField(blank=True, null=True, upload_to='Product_Images')),
                ('Product_Image_3', models.ImageField(blank=True, null=True, upload_to='Product_Images')),
            ],
        ),
    ]
