# Generated by Django 5.1 on 2024-10-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoes_App', '0002_product_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_db',
            old_name='Shoes_Name',
            new_name='Shoes_Brand',
        ),
        migrations.AddField(
            model_name='category_db',
            name='Shoes_Category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
