# Generated by Django 5.1 on 2024-10-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoes_App', '0003_rename_shoes_name_category_db_shoes_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_db',
            old_name='Product_Category',
            new_name='Shoes_Brand',
        ),
        migrations.AddField(
            model_name='product_db',
            name='Shoes_Category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
