# Generated by Django 5.1.2 on 2024-10-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoes_App', '0005_product_db_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_db',
            name='Product_Image_4',
            field=models.ImageField(blank=True, null=True, upload_to='Product_Images'),
        ),
        migrations.AddField(
            model_name='product_db',
            name='Product_Image_5',
            field=models.ImageField(blank=True, null=True, upload_to='Product_Images'),
        ),
    ]
