# Generated by Django 5.1 on 2024-10-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=200, null=True)),
                ('Phone_Number', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Password', models.TextField(blank=True, max_length=200, null=True)),
                ('Confirm_password', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
